/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Controls: typeof import('./src/components/tool/Controls.vue')['default']
    Iframe: typeof import('./src/components/Iframe.vue')['default']
    Presence: typeof import('./src/components/Presence.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StateVisualizer: typeof import('./src/components/tool/StateVisualizer.vue')['default']
    ToastItem: typeof import('./src/components/ToastItem.vue')['default']
    Toolbar: typeof import('./src/components/tool/Toolbar.vue')['default']
    TreeNode: typeof import('./src/components/TreeNode.vue')['default']
  }
}
