/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/aspect-ratio': RouteRecordInfo<
      '/aspect-ratio',
      '/aspect-ratio',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/breadcrumbs': RouteRecordInfo<
      '/breadcrumbs',
      '/breadcrumbs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/calendar': RouteRecordInfo<
      '/calendar',
      '/calendar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/carousel': RouteRecordInfo<
      '/carousel',
      '/carousel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/checkbox': RouteRecordInfo<
      '/checkbox',
      '/checkbox',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/clipboard': RouteRecordInfo<
      '/clipboard',
      '/clipboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collapse': RouteRecordInfo<
      '/collapse',
      '/collapse',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/collapsible': RouteRecordInfo<
      '/collapsible',
      '/collapsible',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/color-picker': RouteRecordInfo<
      '/color-picker',
      '/color-picker',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/combobox': RouteRecordInfo<
      '/combobox',
      '/combobox',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dialog': RouteRecordInfo<
      '/dialog',
      '/dialog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/divider': RouteRecordInfo<
      '/divider',
      '/divider',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dynamic': RouteRecordInfo<
      '/dynamic',
      '/dynamic',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/edit': RouteRecordInfo<
      '/edit',
      '/edit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/file-upload': RouteRecordInfo<
      '/file-upload',
      '/file-upload',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/floating-panel': RouteRecordInfo<
      '/floating-panel',
      '/floating-panel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/hover-card': RouteRecordInfo<
      '/hover-card',
      '/hover-card',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/image': RouteRecordInfo<
      '/image',
      '/image',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/label': RouteRecordInfo<
      '/label',
      '/label',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/menu': RouteRecordInfo<
      '/menu',
      '/menu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/number-input': RouteRecordInfo<
      '/number-input',
      '/number-input',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/otp-input': RouteRecordInfo<
      '/otp-input',
      '/otp-input',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/pagination': RouteRecordInfo<
      '/pagination',
      '/pagination',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/popover': RouteRecordInfo<
      '/popover',
      '/popover',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/presence': RouteRecordInfo<
      '/presence',
      '/presence',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/progress': RouteRecordInfo<
      '/progress',
      '/progress',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/qr-code': RouteRecordInfo<
      '/qr-code',
      '/qr-code',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/radio': RouteRecordInfo<
      '/radio',
      '/radio',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/select': RouteRecordInfo<
      '/select',
      '/select',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/signature': RouteRecordInfo<
      '/signature',
      '/signature',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/slider': RouteRecordInfo<
      '/slider',
      '/slider',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/splitter': RouteRecordInfo<
      '/splitter',
      '/splitter',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/step': RouteRecordInfo<
      '/step',
      '/step',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/switch': RouteRecordInfo<
      '/switch',
      '/switch',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tabs': RouteRecordInfo<
      '/tabs',
      '/tabs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/timer': RouteRecordInfo<
      '/timer',
      '/timer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/toast': RouteRecordInfo<
      '/toast',
      '/toast',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/toggle': RouteRecordInfo<
      '/toggle',
      '/toggle',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tooltip': RouteRecordInfo<
      '/tooltip',
      '/tooltip',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tour': RouteRecordInfo<
      '/tour',
      '/tour',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tree': RouteRecordInfo<
      '/tree',
      '/tree',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/aspect-ratio.vue': {
      routes:
        | '/aspect-ratio'
      views:
        | never
    }
    'src/pages/breadcrumbs.vue': {
      routes:
        | '/breadcrumbs'
      views:
        | never
    }
    'src/pages/calendar.vue': {
      routes:
        | '/calendar'
      views:
        | never
    }
    'src/pages/carousel.vue': {
      routes:
        | '/carousel'
      views:
        | never
    }
    'src/pages/checkbox.vue': {
      routes:
        | '/checkbox'
      views:
        | never
    }
    'src/pages/clipboard.vue': {
      routes:
        | '/clipboard'
      views:
        | never
    }
    'src/pages/collapse.vue': {
      routes:
        | '/collapse'
      views:
        | never
    }
    'src/pages/collapsible.vue': {
      routes:
        | '/collapsible'
      views:
        | never
    }
    'src/pages/color-picker.vue': {
      routes:
        | '/color-picker'
      views:
        | never
    }
    'src/pages/combobox.vue': {
      routes:
        | '/combobox'
      views:
        | never
    }
    'src/pages/dialog.vue': {
      routes:
        | '/dialog'
      views:
        | never
    }
    'src/pages/divider.vue': {
      routes:
        | '/divider'
      views:
        | never
    }
    'src/pages/dynamic.vue': {
      routes:
        | '/dynamic'
      views:
        | never
    }
    'src/pages/edit.vue': {
      routes:
        | '/edit'
      views:
        | never
    }
    'src/pages/file-upload.vue': {
      routes:
        | '/file-upload'
      views:
        | never
    }
    'src/pages/floating-panel.vue': {
      routes:
        | '/floating-panel'
      views:
        | never
    }
    'src/pages/hover-card.vue': {
      routes:
        | '/hover-card'
      views:
        | never
    }
    'src/pages/image.vue': {
      routes:
        | '/image'
      views:
        | never
    }
    'src/pages/label.vue': {
      routes:
        | '/label'
      views:
        | never
    }
    'src/pages/menu.vue': {
      routes:
        | '/menu'
      views:
        | never
    }
    'src/pages/number-input.vue': {
      routes:
        | '/number-input'
      views:
        | never
    }
    'src/pages/otp-input.vue': {
      routes:
        | '/otp-input'
      views:
        | never
    }
    'src/pages/pagination.vue': {
      routes:
        | '/pagination'
      views:
        | never
    }
    'src/pages/popover.vue': {
      routes:
        | '/popover'
      views:
        | never
    }
    'src/pages/presence.vue': {
      routes:
        | '/presence'
      views:
        | never
    }
    'src/pages/progress.vue': {
      routes:
        | '/progress'
      views:
        | never
    }
    'src/pages/qr-code.vue': {
      routes:
        | '/qr-code'
      views:
        | never
    }
    'src/pages/radio.vue': {
      routes:
        | '/radio'
      views:
        | never
    }
    'src/pages/select.vue': {
      routes:
        | '/select'
      views:
        | never
    }
    'src/pages/signature.vue': {
      routes:
        | '/signature'
      views:
        | never
    }
    'src/pages/slider.vue': {
      routes:
        | '/slider'
      views:
        | never
    }
    'src/pages/splitter.vue': {
      routes:
        | '/splitter'
      views:
        | never
    }
    'src/pages/step.vue': {
      routes:
        | '/step'
      views:
        | never
    }
    'src/pages/switch.vue': {
      routes:
        | '/switch'
      views:
        | never
    }
    'src/pages/tabs.vue': {
      routes:
        | '/tabs'
      views:
        | never
    }
    'src/pages/timer.vue': {
      routes:
        | '/timer'
      views:
        | never
    }
    'src/pages/toast.vue': {
      routes:
        | '/toast'
      views:
        | never
    }
    'src/pages/toggle.vue': {
      routes:
        | '/toggle'
      views:
        | never
    }
    'src/pages/tooltip.vue': {
      routes:
        | '/tooltip'
      views:
        | never
    }
    'src/pages/tour.vue': {
      routes:
        | '/tour'
      views:
        | never
    }
    'src/pages/tree.vue': {
      routes:
        | '/tree'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
