/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/checkbox': RouteRecordInfo<'/checkbox', '/checkbox', Record<never, never>, Record<never, never>>,
    '/collapse': RouteRecordInfo<'/collapse', '/collapse', Record<never, never>, Record<never, never>>,
    '/collapsible': RouteRecordInfo<'/collapsible', '/collapsible', Record<never, never>, Record<never, never>>,
    '/combobox': RouteRecordInfo<'/combobox', '/combobox', Record<never, never>, Record<never, never>>,
    '/dialog': RouteRecordInfo<'/dialog', '/dialog', Record<never, never>, Record<never, never>>,
    '/hover-card': RouteRecordInfo<'/hover-card', '/hover-card', Record<never, never>, Record<never, never>>,
    '/image': RouteRecordInfo<'/image', '/image', Record<never, never>, Record<never, never>>,
    '/menu': RouteRecordInfo<'/menu', '/menu', Record<never, never>, Record<never, never>>,
    '/pagination': RouteRecordInfo<'/pagination', '/pagination', Record<never, never>, Record<never, never>>,
    '/popover': RouteRecordInfo<'/popover', '/popover', Record<never, never>, Record<never, never>>,
    '/slider': RouteRecordInfo<'/slider', '/slider', Record<never, never>, Record<never, never>>,
    '/splitter': RouteRecordInfo<'/splitter', '/splitter', Record<never, never>, Record<never, never>>,
    '/switch': RouteRecordInfo<'/switch', '/switch', Record<never, never>, Record<never, never>>,
    '/tabs': RouteRecordInfo<'/tabs', '/tabs', Record<never, never>, Record<never, never>>,
    '/timer': RouteRecordInfo<'/timer', '/timer', Record<never, never>, Record<never, never>>,
    '/tooltip': RouteRecordInfo<'/tooltip', '/tooltip', Record<never, never>, Record<never, never>>,
  }
}
