packages:
  - packages/*
  - packages/*/*
  - shared
  - document
  - storybook

catalogMode: prefer
shellEmulator: true

catalogs:
  build:
    '@sveltejs/package': ^2.5.7
    tsdown: ^0.18.2
  css:
    '@unocss/core': ^66.5.10
    '@unocss/reset': ^66.5.10
    unocss: ^66.5.10
    unocss-preset-animations: ^1.3.0
  font:
    '@fontsource/geist-mono': ^5.2.7
    '@fontsource/geist-sans': ^5.2.5
  frontend:
    '@astrojs/react': ^4.4.2
    '@astrojs/solid-js': ^5.1.3
    '@astrojs/starlight': ^0.37.1
    '@astrojs/svelte': ^7.2.4
    '@astrojs/vue': ^5.1.3
    astro: ^5.16.6
    lit: ^3.3.1
    react: ^19.2.3
    react-dom: ^19.2.3
    solid-js: ^1.9.10
    svelte: ^5.46.0
    vue: ^3.5.26
  hook:
    '@vueuse/core': ^14.1.0
  icon:
    '@iconify-json/carbon': ^1.2.15
    '@iconify-json/catppuccin': ^1.2.17
    '@iconify-json/lineicons': ^1.2.6
    '@iconify-json/logos': ^1.2.10
    '@iconify-json/lucide': ^1.2.82
    '@iconify-json/ph': ^1.2.2
    '@iconify-json/vscode-icons': ^1.2.37
  lint:
    '@antfu/eslint-config': ^6.7.3
    eslint: ^9.39.2
  markdown:
    marked: ^17.0.1
    shiki: ^3.20.0
  plugin:
    '@sveltejs/vite-plugin-svelte': ^6.2.1
    '@vitejs/plugin-react': ^5.1.2
    '@vitejs/plugin-vue': ^6.0.3
    vite-plugin-solid: ^2.11.10
  prod:
    '@floating-ui/dom': 1.7.4
    '@internationalized/date': ^3.10.1
    '@internationalized/number': ^3.6.5
    csstype: ^3.2.3
    perfect-freehand: ^1.2.2
    proxy-compare: ^3.0.1
    proxy-memoize: ^3.0.1
    uqr: ^0.1.2
  script:
    bumpp: ^10.3.2
    plop: ^4.0.4
    rimraf: ^6.1.2
    taze: ^19.9.2
    tsx: ^4.21.0
  store:
    '@nanostores/vue': ^1.0.1
    nanostores: ^1.1.0
  storybook:
    astrobook: ^0.11.2
  test:
    '@vitest/browser': ^4.0.16
    '@vitest/browser-playwright': ^4.0.16
    '@vitest/coverage-v8': ^4.0.16
    '@vitest/eslint-plugin': ^1.6.1
    '@vitest/ui': ^4.0.16
    happy-dom: ^20.0.11
    playwright: ^1.57.0
    vitest: ^4.0.16
    vitest-axe: ^0.1.0
  theme:
    '@pagefind/default-ui': ^1.4.0
    starlight-theme-destyler: ^0.1.7
  types:
    '@types/archiver': ^7.0.0
    '@types/node': ^25.0.3
    '@types/react': ^19.2.7
    '@types/react-dom': ^19.2.3
    ts-morph: ^27.0.2
    typescript: ^5.9.3
  util:
    archiver: ^7.0.1
    cross-env: ^10.1.0
    fast-glob: ^3.3.3
    find-packages: ^10.0.4
    nanoid: ^5.1.6
    sharp: ^0.34.5
  visual:
    node-modules-inspector: ^1.2.0

cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - esbuild
  - sharp
