packages:
  - packages/*
  - packages/*/*
  - examples/*
  - shared
catalog:
  '@antfu/eslint-config': ^4.2.0
  '@internationalized/date': ^3.7.0
  '@internationalized/number': ^3.6.0
  '@types/node': ^22.13.4
  '@types/react': ^19.0.8
  '@types/react-dom': ^19.0.3
  '@zag-js/anatomy': ^0.82.1
  '@zag-js/aria-hidden': ^0.82.1
  '@zag-js/auto-resize': ^0.82.1
  '@zag-js/collection': ^0.82.1
  '@zag-js/color-utils': ^0.82.1
  '@zag-js/core': ^0.82.1
  '@zag-js/date-utils': ^0.82.1
  '@zag-js/dismissable': ^0.82.1
  '@zag-js/dom-event': ^0.80.0
  '@zag-js/dom-query': ^0.82.1
  '@zag-js/element-rect': ^0.82.1
  '@zag-js/element-size': ^0.82.1
  '@zag-js/file-utils': ^0.82.1
  '@zag-js/focus-trap': ^0.82.1
  '@zag-js/focus-visible': ^0.82.1
  '@zag-js/form-utils': ^0.81.1
  '@zag-js/i18n-utils': ^0.82.1
  '@zag-js/interact-outside': ^0.82.1
  '@zag-js/live-region': ^0.82.1
  '@zag-js/number-utils': ^0.80.0
  '@zag-js/numeric-range': ^0.80.0
  '@zag-js/popper': ^0.82.1
  '@zag-js/rect-utils': ^0.82.1
  '@zag-js/remove-scroll': ^0.82.1
  '@zag-js/scroll-snap': ^0.82.1
  '@zag-js/store': ^0.82.1
  '@zag-js/stringify-state': ^0.82.1
  '@zag-js/text-selection': ^0.80.0
  '@zag-js/types': ^0.82.1
  '@zag-js/utils': ^0.82.1
  eslint: ^9.20.1
  find-packages: ^10.0.4
  plop: ^4.0.1
  proxy-compare: ^3.0.1
  proxy-memoize: ^3.0.1
  react: ^19.0.0
  react-dom: ^19.0.0
  rimraf: ^6.0.1
  solid-js: ^1.9.4
  svelte: ^5.20.1
  taze: ^18.5.0
  tsx: ^4.19.2
  typescript: ^5.7.3
  unbuild: ^3.3.1
  uqr: ^0.1.2
  vite: ^6.1.0
  vue: ^3.5.13
catalogs:
  examples:
    '@types/react': ^19.0.8
    '@types/react-dom': ^19.0.3
    '@unocss/reset': ^65.4.3
    '@vitejs/plugin-vue': ^5.2.1
    '@vue/tsconfig': ^0.7.0
    nanoid: ^5.1.0
    react: ^19.0.0
    react-dom: ^19.0.0
    react-router: ^7.1.5
    react-router-dom: ^7.1.5
    unocss: ^65.4.3
    unplugin-auto-import: ^19.0.0
    unplugin-vue-components: ^28.0.0
    unplugin-vue-router: ^0.11.2
    vite: ^6.1.0
    vue: ^3.5.13
    vue-router: ^4.5.0
