packages:
  - packages/*
  - packages/*/*
  - examples/*
  - shared
catalog:
  '@zag-js/core': &zag ^0.80.0
  '@zag-js/anatomy': *zag
  '@zag-js/aria-hidden': *zag
  '@zag-js/collection': *zag
  '@zag-js/dismissable': *zag
  '@zag-js/dom-event': *zag
  '@zag-js/dom-query': *zag
  '@zag-js/focus-trap': *zag
  '@zag-js/focus-visible': *zag
  '@zag-js/form-utils': *zag
  '@zag-js/popper': *zag
  '@zag-js/remove-scroll': *zag
  '@zag-js/store': *zag
  '@zag-js/types': *zag
  '@zag-js/utils': *zag
  '@zag-js/rect-utils': *zag
  '@zag-js/element-rect': *zag
  '@zag-js/number-utils': *zag
  '@zag-js/element-size': *zag
  '@zag-js/numeric-range': *zag
  '@zag-js/auto-resize': *zag
  '@zag-js/color-utils': *zag
  '@zag-js/date-utils': *zag
  '@zag-js/interact-outside': *zag
  '@zag-js/stringify-state': *zag
  '@zag-js/text-selection': *zag
  '@zag-js/scroll-snap': *zag
  '@zag-js/live-region': *zag
  '@zag-js/file-utils': *zag
  '@zag-js/i18n-utils': *zag

  '@internationalized/date': &internationalized ^3.6.0
  '@internationalized/number': *internationalized

  eslint: ^9.17.0
  '@antfu/eslint-config': ^3.12.1

  '@types/node': ^22.10.3
  find-packages: ^10.0.4
  plop: ^4.0.1
  rimraf: ^6.0.1
  taze: ^0.18.0
  tsx: ^4.19.2
  typescript: ^5.7.2
  unbuild: ^3.2.0
  uqr: ^0.1.2

  vite: &vite ^6.0.6

  solid-js: &solid ^1.9.3

  vue: &vue ^3.5.13

  svelte: &svelte ^5.16.0

  react: &react ^18.3.1
  react-dom: *react
  '@types/react': *react
  '@types/react-dom': *react

  proxy-compare: &proxy ^3.0.1
  proxy-memoize: *proxy
catalogs:
  examples:
    unocss: &unocss ^0.65.3
    '@unocss/reset': *unocss

    '@vitejs/plugin-vue': ^5.2.1

    nanoid: ^5.0.9

    unplugin-auto-import: ^0.19.0
    unplugin-vue-components: ^0.28.0
    unplugin-vue-router: ^0.10.9

    vite: *vite

    vue: *vue
    vue-router: ^4.5.0
    '@vue/tsconfig': ^0.7.0
