packages:
  - packages/*
  - packages/*/*
  - examples/*
  - shared

catalogs:
  core:
    '@internationalized/date': ^3.7.0
    '@internationalized/number': ^3.6.0
    '@floating-ui/dom': 1.7.1
    proxy-compare: ^3.0.1
    proxy-memoize: ^3.0.1
    uqr: ^0.1.2
    csstype: ^3.1.3
  type:
    typescript: ^5.7.3
    eslint: ^9.20.1
    '@types/node': ^22.13.4
    '@antfu/eslint-config': ^4.2.0
    '@vue/tsconfig': ^0.7.0
  build:
    unbuild: ^3.3.1
    bumpp: ^10.0.3
    '@sveltejs/package': ^2.3.10
  frameworks:
    '@types/react': ^19.0.8
    '@types/react-dom': ^19.0.3
    '@types/react-router-config': ^5.0.11
    '@types/react-router-dom': ^5.3.3
    react: ^19.0.0
    react-dom: ^19.0.0
    react-router: ^7.1.5
    react-router-dom: ^7.1.5
    vue: ^3.5.13
    vue-router: ^4.5.0
    solid-js: ^1.9.4
    '@solidjs/router': ^0.15.3
    svelte: ^5.20.1
    svelte-check: ^4.1.4
    svelte-routing: ^2.13.0
    '@tsconfig/svelte': ^5.0.4
  plugin:
    '@vitejs/plugin-vue': ^5.2.1
    vite-plugin-solid: ^2.11.0
    unplugin-auto-import: ^19.0.0
    unplugin-vue-components: ^28.0.0
    unplugin-vue-router: ^0.11.2
    unplugin-react-components: ^0.1.4
    vite-plugin-pages: ^0.32.4
    '@vitejs/plugin-react': ^4.3.4
    '@sveltejs/vite-plugin-svelte': ^5.0.3
  runtime:
    vite: ^6.1.0
    globals: ^15.14.0
    cross-env: ^7.0.3
  test:
    vitest: ^3.2.4
    '@vitest/ui': ^3.2.4
    '@vitest/eslint-plugin': ^1.2.7
    playwright: ^1.53.1
    '@vitest/browser': ^3.2.4
    vitest-browser-vue: ^1.0.0
    vitest-browser-svelte: ^1.0.0
    vitest-browser-react: ^1.0.0
    vitest-browser-solid: ^0.1.4
    vitest-axe: ^0.1.0
  css:
    unocss: ^65.4.3
    '@unocss/reset': ^65.4.3
  util:
    rimraf: ^6.0.1
    taze: ^18.5.0
    tsx: ^4.19.2
    plop: ^4.0.1
    nanoid: ^5.1.0
  icon:
    '@iconify-json/carbon': ^1.2.6
onlyBuiltDependencies:
  - esbuild
