packages:
  - 'packages/*'
  - 'packages/*/*'
  - utils
catalog:
  '@antfu/eslint-config': ^3.12.0
  '@types/node': ^22.10.2
  '@storybook/web-components-vite': ^8.4.7
  '@storybook/web-components': ^8.4.7
  '@lit-labs/signals': ^0.1.1
  '@lit/context': ^1.1.3
  alien-signals: ^0.4.4
  lit: ^3.2.1
  eslint: ^9.16.0
  rimraf: ^6.0.1
  typescript: ^5.7.2
  vite: ^6.0.3
  storybook: ^8.4.7
