packages:
  - 'packages/*'
  - 'packages/*/*'
  - 'examples/*'
  - utils

catalog:
  '@antfu/eslint-config': ^3.12.0
  '@types/node': ^22.10.2
  '@zag-js/anatomy': ^0.79.2
  '@zag-js/core': ^0.79.2
  '@zag-js/dom-event': ^0.79.2
  '@zag-js/dom-query': ^0.79.2
  '@zag-js/types': ^0.79.2
  '@zag-js/utils': ^0.79.2
  '@zag-js/focus-visible': ^0.79.2
  '@zag-js/form-utils': ^0.79.2
  eslint: ^9.16.0
  rimraf: ^6.0.1
  typescript: ^5.7.2
  unbuild: ^3.2.0
  vite: ^6.0.5
  plop: ^4.0.1

catalogs:
  examples:
    '@unocss/reset': ^0.65.3
    unocss: ^0.65.3
    nanoid: ^5.0.9
