packages:
  - packages/*
  - packages/*/*
  - examples/*
  - utils
catalog:
  '@antfu/eslint-config': ^3.12.1
  '@types/node': ^22.10.3
  '@zag-js/anatomy': ^0.80.0
  '@zag-js/aria-hidden': ^0.80.0
  '@zag-js/collection': ^0.80.0
  '@zag-js/core': ^0.80.0
  '@zag-js/dismissable': ^0.80.0
  '@zag-js/dom-event': ^0.80.0
  '@zag-js/dom-query': ^0.80.0
  '@zag-js/focus-trap': ^0.80.0
  '@zag-js/focus-visible': ^0.80.0
  '@zag-js/form-utils': ^0.80.0
  '@zag-js/popper': ^0.80.0
  '@zag-js/remove-scroll': ^0.80.0
  '@zag-js/store': ^0.80.0
  '@zag-js/types': ^0.80.0
  '@zag-js/utils': ^0.80.0
  '@zag-js/rect-utils': ^0.80.0
  eslint: ^9.17.0
  find-packages: ^10.0.4
  plop: ^4.0.1
  rimraf: ^6.0.1
  taze: ^0.18.0
  tsx: ^4.19.2
  typescript: ^5.7.2
  unbuild: ^3.2.0
  vite: ^6.0.6
  vue: ^3.5.13
catalogs:
  examples:
    '@unocss/reset': ^0.65.3
    '@vitejs/plugin-vue': ^5.2.1
    '@vue/tsconfig': ^0.7.0
    nanoid: ^5.0.9
    unocss: ^0.65.3
    unplugin-auto-import: ^0.19.0
    unplugin-vue-components: ^0.28.0
    unplugin-vue-router: ^0.10.9
    vite: ^6.0.6
    vue: ^3.5.13
    vue-router: ^4.5.0
