export { Component } from './src/component'
export type { ComponentOptions, ContextSource } from './src/component'
export { createPortal, Portal } from './src/components/portal'
export { useActor } from './src/hooks/use-actor'
export { useService } from './src/hooks/use-service'
export { useSnapshot } from './src/hooks/use-snapshot'
export { normalizeProps } from './src/normalize-props'
export type { AttrMap } from './src/normalize-props'
export { spread } from './src/spread'
export { hydrateSpreadProps, spreadProps } from './src/spread-props'
export { useMachine } from './src/use-machine'
export { mergeProps } from '@destyler/xstate'
export type { ContextFrom, EventFrom, StateFrom } from '@destyler/xstate'
