export { DestylerTabsContent, destylerTabsContentProps, type DestylerTabsContentProps } from './components/content'
export { DestylerTabsIndicator, destylerTabsIndicatorProps, type DestylerTabsIndicatorProps } from './components/indicator'
export { DestylerTabsList, destylerTabsListProps, type DestylerTabsListProps } from './components/list'
export { DestylerTabsRoot, destylerTabsRootProps, type DestylerTabsRootProps } from './components/root'
export { DestylerTabsTrigger, destylerTabsTriggerProps, type DestylerTabsTriggerProps } from './components/trigger'
