export { DestylerCollapseRoot, type DestylerCollapseRootProps } from './components/root'
export { DestylerCollapseHeader, type DestylerCollapseHeaderProps } from './components/header'
export { DestylerCollapseContent, type DestylerCollapseContentProps } from './components/content'
export { DestylerCollapseItem, type DestylerCollapseItemProps } from './components/item'
export { DestylerCollapseTrigger, type DestylerCollapseTriggerProps } from './components/trigger'
