export { MachineController } from './src/controllers/machine-controller'
export { spread, SpreadDirective, spreadEvents, SpreadEventsDirective, spreadProps, SpreadPropsDirective } from './src/directives/spread-props'
export { normalizeProps } from './src/utils/normalize-props'
export { mergeProps } from '@destyler/xstate'
export type { ContextFrom, EventFrom, StateFrom } from '@destyler/xstate'
