/* generated by unplugin-react-components */
export {}
declare global{
	const Breadcrumbs: typeof import('./src/pages/breadcrumbs')['default']
	const StateVisualizer: typeof import('./src/components/tool/StateVisualizer')['StateVisualizer']
	const Toolbar: typeof import('./src/components/tool/Toolbar')['Toolbar']
}