/* generated by unplugin-react-components */
export {}
declare global{
	const IFrame: typeof import('./src/components/IFrame')['IFrame']
	const ToastItem: typeof import('./src/components/ToastItem')['ToastItem']
	const TreeNode: typeof import('./src/components/TreeNode')['TreeNode']
	const Breadcrumbs: typeof import('./src/pages/breadcrumbs')['default']
	const ColorPicker: typeof import('./src/pages/color-picker')['default']
	const Divider: typeof import('./src/pages/divider')['default']
	const FileUpload: typeof import('./src/pages/file-upload')['default']
	const FloatingPanel: typeof import('./src/pages/floating-panel')['default']
	const HoverCard: typeof import('./src/pages/hover-card')['default']
	const Presence: typeof import('./src/pages/presence')['Presence']
	const Timer: typeof import('./src/pages/timer')['default']
	const Toast: typeof import('./src/pages/toast')['default']
}