name: Add Label to PR

on:
  pull_request:
    types: [opened]

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
    - name: Add label to PR
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.rest.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['in progress']
          })
