name: Docs

on:
  pull_request:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install
        run: pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm run docs:build

      - name: Zip
        run: pnpm run docs:zip

      - name: Install dependencies (ubuntu only)
        run: |
          sudo apt-get update
          sudo apt-get install -y httpie

      - name: Deploy
        run: |
          http --ignore-stdin --form --follow --timeout 3600 POST 'https://gateway.zeabur.com/projects/66d7177c6552069ec1cfa5e7/services/66e00fe375dfa2d73010e0a0/deploy' \
          'code'@/home/runner/work/destyler/destyler/.docs/.vitepress/zip/dist.zip \
          'environment'='66d7177c021a5e008543161a' \
          Content-Type:'application/zip' \
          Authorization:'${{secrets.ZEABUR_TOKEN}}'
